/** @format */

import { StyleSheet, Dimensions } from 'react-native';

const commonTextStyle = {
	fontFamily: 'Roboto',
	fontStyle: 'normal',
	fontWeight: '400',
	fontSize: 16,
	lineHeight: 20,
	color: '#212121',
};

const styles = StyleSheet.create({
	container: {
		backgroundColor: 'rgba(208, 211, 217, 0.90)',
	},
	rootContainer: {
		width: '100%',
		height: '100%',
		backgroundColor: '#fff',
	},
	image: {
		width: '100%',
		height: '100%',
		justifyContent: 'flex-end',
		alignItems: 'center',
	},
	avatarContainer: {
		position: 'absolute',
		top: 0,
		backgroundColor: '#F6F6F6',
		borderRadius: 16,
	},
	addAvatar: {
		width: 25,
		height: 25,
		position: 'absolute',
		right: 0,
		bottom: 13,
		transform: [{ translateX: 12.5 }],
	},
	avatar: {
		flex: 1,
		width: '100%',
		height: '100%',
		borderRadius: 16,
	},
	title: {
		...commonTextStyle,
		textAlign: 'center',
		marginBottom: 32,
		textAlign: 'center',
		fontSize: 30,
		lineHeight: 30,
		fontWeight: '500',
		letterSpacing: 0.3,
	},
	form: {
		backgroundColor: '#fff',
		width: '100%',
		borderTopLeftRadius: 25,
		borderTopRightRadius: 25,
		paddingTop: 32,
		paddingLeft: 16,
		paddingRight: 16,
	},
	formReg: {
		position: 'relative',
		backgroundColor: '#fff',
		width: '100%',
		borderTopLeftRadius: 25,
		borderTopRightRadius: 25,
		paddingTop: 92,
		paddingLeft: 16,
		paddingRight: 16,
	},
	profile: {
		position: 'relative',
		backgroundColor: '#fff',
		width: '100%',
		borderTopLeftRadius: 25,
		borderTopRightRadius: 25,
		marginTop: 147,
		paddingTop: 92,
		paddingLeft: 16,
		paddingRight: 16,
	},
	inputBox: {
		display: 'flex',
		gap: 16,
		marginBottom: 43,
		color: '#BDBDBD',
	},
	inputPassContainer: {
		position: 'relative',
	},
	input: {
		...commonTextStyle,
		width: '100%',
		minHeight: 50,
		backgroundColor: '#F6F6F6',
		borderColor: '#E8E8E8',
		borderWidth: 1,
		borderRadius: 12,
		padding: 16,
	},
	inputPost: {
		...commonTextStyle,
		width: '100%',
		height: 50,
		backgroundColor: '#FFF',
		borderBottomColor: '#E8E8E8',
		borderBottomWidth: 1,
		padding: 16,
	},
	inputPostLocation: {
		...commonTextStyle,
		width: '100%',
		paddingLeft: 4,
		paddingRight: 16,
	},
	inputLocation: {
		flexDirection: 'row',
		alignItems: 'center',
		width: '100%',
		height: 50,
		backgroundColor: '#FFF',
		borderBottomColor: '#E8E8E8',
		borderBottomWidth: 1,
		color: '#BDBDBD',
		padding: 16,
	},
	inputCommentContainer: {
		paddingLeft: 16,
		paddingRight: 16,
		marginBottom: 10,
	},
	inputComment: {
		...commonTextStyle,
		fontWeight: '500',
		width: '100%',
		height: 50,
		backgroundColor: '#F6F6F6',
		borderColor: '#E8E8E8',
		borderRadius: 25,
		borderWidth: 1,
		paddingLeft: 16,
		paddingRight: 16,
	},
	sendComment: {
		position: 'absolute',
		width: 34,
		height: 34,
		right: 24,
		top: 8,
	},
	focusedInput: {
		borderColor: '#FF6C00',
	},
	focusedInputPost: {
		width: '100%',
		borderBottomColor: '#FF6C00',
	},
	showPasswordButton: {
		position: 'absolute',
		right: 16,
		top: 16,
	},
	showPasswordText: {
		...commonTextStyle,
		color: '#1B4371',
		textAlign: 'right',
	},
	buttonBox: {
		display: 'flex',
		gap: 16,
		paddingBottom: 132,
	},
	buttonPostContainer: {
		flex: 1,
		flexDirection: 'column',
		justifyContent: 'space-between',
	},
	inputPostContainer: {
		display: 'flex',
		rowGap: 16,
		marginBottom: 32,
		color: '#BDBDBD',
	},
	button: {
		backgroundColor: '#FF6C00',
		borderRadius: 100,
	},
	buttonNonActive: {
		backgroundColor: '#F6F6F6',
		borderRadius: 100,
	},
	buttonDel: {
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		width: 70,
		height: 40,
		borderRadius: 100,
		backgroundColor: '#F6F6F6',
		marginLeft: 'auto',
		marginRight: 'auto',
		color: '#BDBDBD',
	},
	buttonText: {
		...commonTextStyle,
		color: '#FFF',
		textAlign: 'center',
		paddingTop: 16,
		paddingLeft: 32,
		paddingRight: 32,
		paddingBottom: 16,
	},
	singupLink: {
		width: '100%',
	},
	signup: {
		...commonTextStyle,
		color: '#1B4371',
		textAlign: 'center',
	},
	mainTitle: {
		position: 'relative',
		paddingTop: 11,
		paddingBottom: 11,
		borderBottomColor: '#BDBDBD',
		borderBottomWidth: 1,
	},
	mainText: {
		...commonTextStyle,
		textAlign: 'center',
		fontSize: 18,
		fontWeight: '500',
		lineHeight: 22,
		letterSpacing: -0.408,
	},
	quitButton: {
		position: 'absolute',
		right: 16,
		top: 11,
	},
	backButton: {
		position: 'absolute',
		left: 16,
		top: 11,
	},
	postContainer: {
		flex: 1,
		paddingTop: 32,
		paddingBottom: 32,
		paddingLeft: 16,
		paddingRight: 16,
	},
	commentList: {
		flex: 1,
		flexDirection: 'column',
		paddingTop: 32,
		paddingBottom: 2,
		paddingLeft: 16,
		paddingRight: 16,
	},
	post: {
		...commonTextStyle,
		fontSize: 13,
		fontWeight: '700',
		textAlign: 'left',
	},
	photoUpload: {
		...commonTextStyle,
		width: '100%',
		color: '#BDBDBD',
		marginBottom: 32,
		marginLeft: 'auto',
		marginRight: 'auto',
	},
	avatarImg: {
		backgroundColor: '#F1F1F1',
		width: 60,
		height: 60,
		borderRadius: 16,
		overflow: 'hidden',
	},
	userContainer: {
		display: 'flex',
		flexDirection: 'row',
		columnGap: 8,
		alignItems: 'center',
		marginBottom: 32,
	},
	userName: {
		fontSize: 13,
		fontWeight: '700',
	},
	userEmail: {
		...commonTextStyle,
		color: 'rgba(33, 33, 33, 0.80)',
		fontSize: 11,
	},
	photoContainer: {
		display: 'flex',
		justifyContent: 'flex-start',
		alignItems: 'flex-end',
		width: '100%',
		minHeight: 240,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: '#E8E8E8',
		backgroundColor: '#F6F6F6',
		marginLeft: 'auto',
		marginRight: 'auto',
		marginBottom: 8,
	},
	camera: {
		position: 'absolute',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		padding: 18,
		backgroundColor: '#fff',
		borderRadius: 50,
		zIndex: 999,
		opacity: 0.1,
	},
	nameUser: {
		...commonTextStyle,
		marginBottom: 33,
		textAlign: 'center',
		fontSize: 30,
		fontWeight: '500',
		letterSpacing: 0.3,
		lineHeight: 30,
	},
	postList: {
		display: 'flex',
		rowGap: 32,
		paddingBottom: 43,
	},
	img: {
		width: '100%',
		minHeight: 240,
		maxHeight: 260,
		borderRadius: 8,
		resizeMode: 'cover',
	},
	postPhotoTitle: {
		...commonTextStyle,
		fontWeight: '500',
	},
	postDetail: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	postDetailFeedback: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		columnGap: 24,
	},
	postDetailItem: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		columnGap: 6,
	},
	postDetailLocation: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		columnGap: 4,
	},
	postDetailText: {
		...commonTextStyle,
	},
	linkText: {
		maxWidth: 250,
	},
	mapTitle: {
		...commonTextStyle,
		padding: 15,
		fontSize: 18,
		fontWeight: '500',
		lineHeight: 24,
	},
	mapContainer: {
		width: '100%',
		minHeight: 440,
		maxHeight: 550,
		borderColor: '#212121',
		borderWidth: 1,
		marginBottom: 30,
	},
	country: {
		color: 'darkblue',
	},
	userComment: {
		display: 'flex',
		flexDirection: 'row',
		columnGap: 16,
		width: '100%',
	},
	userCommentMirror: {
		flexDirection: 'row-reverse',
	},
	userIcon: {
		width: 28,
		height: 28,
		backgroundColor: '#979797',
		borderRadius: '50%',
	},
	timeComment: {
		color: '#BDBDBD',
		textAlign: 'right',
		fontSize: 10,
		lineHeight: 10,
	},
	timeCommentMirror: {
		textAlign: 'left',
	},
	userCommentTextBox: {
		flex: 1,
		gap: 8,
		borderBottomLeftRadius: 6,
		borderBottomRightRadius: 6,
		backgroundColor: 'rgba(0, 0, 0, 0.03)',
		padding: 16,
	},
	userCommentText: {
		color: '#212121',
		fontSize: 13,
		lineHeight: 18,
	},
	mapStyle: {
		width: '100%',
		height: '100%',
		borderRadius: 8,
	},
	cameraBox: {
		width: '100%',
		height: '100%',
		borderWidth: 1,
		borderColor: '#212121',
		borderRadius: 10,
		overflow: 'hidden',
	},
	photoView: {
		alignSelf: 'left',
		flex: 1,
		backgroundColor: 'transparent',
		justifyContent: 'flex-start',
	},
	photoTake: {
		flex: 1,
		justifyContent: 'flex-end',
		padding: 10,
	},
	flipContainer: {
		flex: 0.1,
		alignSelf: 'flex-end',
	},
	buttonCamera: {
		alignSelf: 'center',
	},
	takePhotoOut: {
		borderWidth: 2,
		borderColor: 'white',
		height: 50,
		width: 50,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		borderRadius: 50,
	},
	takePhotoInner: {
		borderWidth: 2,
		borderColor: 'white',
		height: 40,
		width: 40,
		backgroundColor: 'white',
		borderRadius: 50,
	},
});

export default styles;
